export enum AuditAction {
  // Brand Pages
  UPDATE_BRAND = 'UPDATE_BRAND',

  // Job Positions
  CREATE_JOB_POSITION = 'CREATE_JOB_POSITION',
  UPDATE_JOB_POSITION = 'UPDATE_JOB_POSITION',
  DELETE_JOB_POSITION = 'DELETE_JOB_POSITION',
  TOGGLE_JOB_POSITION_STATUS = 'TOGGLE_JOB_POSITION_STATUS',

  // Job Applications
  SUBMIT_JOB_APPLICATION = 'SUBMIT_JOB_APPLICATION',
  DELETE_JOB_APPLICATION = 'DELETE_JOB_APPLICATION',

  // Corporate Identity
  CREATE_CORPORATE_IDENTITY = 'CREATE_CORPORATE_IDENTITY',
  UPDATE_CORPORATE_IDENTITY = 'UPDATE_CORPORATE_IDENTITY',
  DELETE_CORPORATE_IDENTITY = 'DELETE_CORPORATE_IDENTITY',

  // ITalks / Interactive
  CREATE_I_TALKS = 'CREATE_I_TALKS',
  UPDATE_I_TALKS = 'UPDATE_I_TALKS',
  DELETE_I_TALKS = 'DELETE_I_TALKS',

  // Messages
  SUBMIT_CONTACT_FORM = 'SUBMIT_CONTACT_FORM',
  DELETE_MESSAGE = 'DELETE_MESSAGE',

  // News
  CREATE_NEWS = 'CREATE_NEWS',
  UPDATE_NEWS = 'UPDATE_NEWS',
  DELETE_NEWS = 'DELETE_NEWS',
  SYNC_NEWS_CATEGORIES = 'SYNC_NEWS_CATEGORIES',

  // Sliders & Stats
  CREATE_SLIDER = 'CREATE_SLIDER',
  UPDATE_SLIDER = 'UPDATE_SLIDER',
  DELETE_SLIDER = 'DELETE_SLIDER',
  UPDATE_STAT = 'UPDATE_STAT',

  // Team
  CREATE_TEAM_MEMBER = 'CREATE_TEAM_MEMBER',
  UPDATE_TEAM_MEMBER = 'UPDATE_TEAM_MEMBER',
  DELETE_TEAM_MEMBER = 'DELETE_TEAM_MEMBER',

  // Trash Bin
  MOVE_TO_TRASH = 'MOVE_TO_TRASH',
  RESTORE_FROM_TRASH = 'RESTORE_FROM_TRASH',
  DELETE_PERMANENTLY = 'DELETE_PERMANENTLY',

  // Volunteers
  SUBMIT_VOLUNTEER_FORM = 'SUBMIT_VOLUNTEER_FORM',
  DELETE_VOLUNTEER = 'DELETE_VOLUNTEER',
}

export interface LogDetails {
  title?: string;
  slug?: string;
  reason?: string;
  [key: string]: unknown;
}
